events {}

# Por defecto se usa el algoritmo round-robin (turnos rotativos)
http {
    upstream flask_servers { # Define un grupo de servidores backend para balanceo de carga
        server servidor1:5000;
        server servidor2:5000;
    }

    server {
        listen 80;

        location / { # Configura la ubicación raíz para redirigir las solicitudes a los servidores backend
            proxy_pass http://flask_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
